#spring:
#  application:#    name: sparrow-authorization-server

#logging:
#  level:
#    root: DEBUG


#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:6060/.well-known/jwks.json
#          issuer-uri: http://localhost:6060