swagger: "2.0"
info:
  description: "认证中心，用于身份认证和账户的管理"
  version: "1.0.0"
  title: "组织权限管理"
  contact:
    email: "fanmeijian@aliyun.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:6060"
basePath: "/"
tags:
- name: "认证"

schemes:
- "http"
paths:
  /oauth2/token:
    post:
      tags:
      - "认证"
      summary: "登录"
      parameters:
      - name: "body"
        in: "body"
        schema:
          $ref: "#/definitions/Oauth"
      responses:
        "200":
          description: "成功"
  /oauth2/password:
    post:
      tags:
      - "认证"
      summary: "修改密码"
      parameters:
      - name: "body"
        in: "body"
        schema:
          allOf: 
          - $ref: "#/definitions/Oauth"
          type: "object"
          properties:
            oldPassword:
              type: "string"
            secondPassword:
              type: "string"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Authorization: []
    put:
      tags:
      - "认证"
      summary: "重置密码"
      parameters:
      - name: "body"
        in: "body"
        schema:
          $ref: "#/definitions/Oauth"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Authorization: []
      
definitions:    
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
      type:
        type: "string"
      message:
        type: "string"
          
  Oauth:
    type: "object"
    properties: 
      username:
        type: "string"
      password:
        type: "string"