swagger: "2.0"
info:
  description: "认证中心，用于身份认证和账户的管理"
  version: "1.0.0"
  title: "组织权限管理"
  contact:
    email: "fanmeijian@aliyun.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:6060"
basePath: "/"
tags:
- name: "认证"

schemes:
- "http"
paths:
  /oauth/token:
    post:
      tags:
      - "认证"
      summary: "登录"
      parameters:
      - name: "username"
        in: "query"
        type: "string"
      - name: "password"
        in: "query"
        type: "string"
      - name: "client_id"
        in: "query"
        type: "string"   
      - name: "client_secret"
        in: "query"
        type: "string"
      - name: "grant_type"
        in: "query"
        type: "string"
        description: "[password]"
      responses:
        "200":
          description: "成功"
